[build]
target = "index.html"
dist = "dist"
public_url = "/"

[watch]
watch = ["src", "styles", "index.html"]
ignore = ["styles/tailwind.css"]

[[hooks]]
stage = "pre_build"
command = "npm"
command_arguments = ["run", "build:css"]
